const fs = require('fs');
const path = require('path');

const contentEnDir = path.join(__dirname, 'content', 'en');
const contentFrDir = path.join(__dirname, 'content', 'fr');

fs.mkdirSync(contentEnDir, { recursive: true });
fs.mkdirSync(contentFrDir, { recursive: true });

const siteEn = {
  nav_about: 'About',
  nav_experience: 'Experience',
  nav_projects: 'Projects',
  nav_education: 'Education',
  nav_contact: 'Contact',
  hero_greeting: 'Hi, my name is',
  hero_name: 'Angesh Chanderdip.',
  hero_subtitle: 'I engineer secure access for a connected world.',
  hero_description: 'I am a Cybersecurity Engineer specializing in network access control and endpoint security. With a passion for automation and a proven record in Fortune 500 environments, I design and defend robust, identity-driven security frameworks.',
  hero_cta: 'Get in Touch',
  about_title: 'About Me',
  about_description_1: "Hello! I'm Angesh, a cybersecurity professional passionate about making secure access seamless. I love working in cybersecurity because it combines what I enjoy most — understanding how systems connect, predicting where things could go wrong, and making sure people can work safely and smoothly.",
  about_description_2: "Over the years, I’ve focused on securing access within large, complex networks using tools like Cisco ISE, strong endpoint protection, and automation. I’m a big believer that security shouldn’t get in the way but it should make everything run better. That’s why I use scripting and smart workflows to reduce the repetitive stuff and help teams respond faster when issues arise.",
  about_description_3: "At the end of the day, my mission is simple: build trust into technology so organizations can stay connected, stay safe, and keep moving forward.",
  about_description_4: "Let’s secure the future — one connection at a time.",
  skills_title: 'My Arsenal of Skills',
  experience_title: 'Where I’ve Worked',
  experience_professional_title: 'Professional Experience',
  experience_volunteer_title: 'Volunteer & Community',
  projects_title: 'Things I’ve Built',
  education_title: 'Education & Certifications',
  education_tab_degree: 'My Education',
  education_tab_certs: 'Certifications',
  education_tab_future: 'Future Plans',
  future_plans_title: 'Continuous Learning & Growth',
  future_plans_description: 'The cybersecurity landscape is ever-evolving, and so am I. I am committed to staying at the forefront of the industry. Here are my current strategic directives:',
  future_plans_isc2cc: "Establish a comprehensive, vendor-neutral foundation in cybersecurity principles. This certification validates essential knowledge across key domains, including access controls, network security, security operations, and the core tenets of confidentiality, integrity, and availability required for any security role.",
  future_plans_ccna: "Achieve mastery of modern network infrastructure by validating core skills in network access, IP connectivity, and security fundamentals. This certification will solidify expertise in configuring and managing wired and wireless networks, understanding network automation, and implementing foundational security policies on Cisco devices.",
  future_plans_az500: "Deepen expertise in cloud security by mastering the implementation of advanced security controls and threat protection in Microsoft Azure. This involves managing identity and access, securing networking, hardening virtual machines, and orchestrating security operations to protect data, applications, and infrastructure at enterprise scale.",
  future_plans_az204: "Bridge the gap between development and security by gaining proficiency in building, testing, and maintaining secure cloud-native applications on Azure. Key skills include implementing secure Azure solutions, developing for Azure storage, and integrating authentication and authorization to embed security throughout the software development lifecycle.",
  future_plans_competencies_title: 'Key Competencies',
  cert_desc_btl1: "Validates practical, hands-on skills for real-world defensive security. Holders have demonstrated proficiency in threat intelligence, network security monitoring, digital forensics, and incident response across a wide range of platforms and scenarios.",
  cert_desc_sixsigma_white: "Provides a foundational overview of the Six Sigma methodology. White Belts understand the basic concepts, vocabulary, and their roles within a quality-focused organization, enabling them to support improvement projects.",
  cert_desc_sixsigma_yellow: "Validates a solid understanding of Six Sigma principles. Yellow Belts are valuable team members on projects, capable of applying basic tools, collecting data, and understanding process maps to assist Green and Black Belts.",
  cert_desc_sixsigma_green: "Demonstrates proficiency in leading and executing process improvement projects. Green Belts are experts in the DMAIC framework, utilizing statistical analysis and project management skills to solve quality problems and deliver tangible business results.",
  cert_desc_sixsigma_black: "The highest level of Six Sigma certification. Black Belts are experts in advanced statistical analysis and project leadership, capable of managing complex, cross-functional improvement projects that drive significant organizational change and financial benefits.",
  cert_desc_cct: "Validates essential skills for on-site support and maintenance of Cisco networking and system devices. Focuses on remedial services, hardware replacement, and configuration to restore functionality, ensuring operational continuity.",
  cert_desc_az900: "Provides a foundational understanding of cloud concepts and core Microsoft Azure services. It covers cloud principles, Azure architecture, security, privacy, compliance, and trust, as well as Azure pricing and support.",
  cert_desc_isc2_candidate: "Recognizes individuals on their path to achieving a full (ISC)² certification like the CISSP. It signifies a commitment to the cybersecurity profession and adherence to the (ISC)² Code of Ethics while gaining the necessary work experience.",
  cert_desc_cy_analyst: "Focuses on the skills required for a Security Operations Center (SOC) analyst, including threat monitoring, detection, and analysis. It covers behavioral analytics to identify and combat malware and advanced persistent threats (APTs).",
  cert_desc_cloud_plus: "Demonstrates the skills needed to implement and maintain cloud technologies. It validates knowledge of cloud security controls, infrastructure management, and best practices for deploying and automating secure cloud environments.",
  cert_desc_ccna: "A foundational networking certification that validates the ability to install, configure, operate, and troubleshoot medium-sized routed and switched networks. It also includes verification and implementation of connections to remote sites in a WAN.",
  cert_desc_cissp_cns: "Covers a core domain of the CISSP, focusing on securing network architecture, communication channels, and mitigating network-based attacks. Validates expertise in protocols, segmentation, and wireless security.",
  cert_desc_win10_ad: "Demonstrates proficiency in managing and securing Windows 10 endpoints within an Active Directory environment. Covers Group Policy Objects (GPOs), user and computer account management, and troubleshooting client connectivity.",
  cert_desc_secplus_threats: "Focuses on identifying and analyzing threat actors, intelligence sources, and system vulnerabilities. This credential validates the ability to use threat intelligence to support organizational security and proactively hunt for threats.",
  cert_desc_az_admin_aad: "Covers core skills for administering Azure Active Directory, including tenant and domain management, Enterprise State Roaming, Identity Protection, and Self-Service Password Reset (SSPR).",
  cert_desc_sec_risk_mgmt: "Validates expertise in managing security controls through a structured approach, covering risk management, user security, session management, and data encryption techniques.",
  cert_desc_ws2016_gpo: "Validates proficiency in the function, configuration, and processing of Active Directory Group Policy Objects (GPOs) for centralized configuration management in Windows Server 2016 environments.",
  contact_title: 'Establish Connection',
  contact_subtitle: 'Connect\nwith me',
  contact_description: "I'm always interested in new challenges and opportunities. My digital door is always open. Whether you have a question, a project proposal, or just want to connect, feel free to reach out. Use the direct relays for quick contact or the secure form for encrypted messaging.",
  contact_direct_relay_title: 'Direct Relays',
  contact_transmission_form_title: 'Secure Transmission',
  contact_form_name: 'Your Name',
  contact_form_name_placeholder: 'e.g., Ada Lovelace',
  contact_form_email: 'Your Email',
  contact_form_email_placeholder: 'e.g., user@domain.com',
  contact_form_subject: 'Subject',
  contact_form_subject_placeholder: 'Project Proposal',
  contact_form_message: 'Your Message',
  contact_form_submit: 'Send Message',
  contact_sending_status: 'Transmitting...',
  contact_success_title: 'Transmission Complete',
  contact_success_desc: "Your message has been securely relayed. Thanks for reaching out—I'll get back to you shortly!",
  contact_error_title: 'Transmission Failed',
  contact_error_desc: "A data packet was lost along the way. Please check your connection and try again.",
  contact_send_another: 'Compose New Message',
  contact_retry_button: 'Try Again',
  validation_name_required: 'Your name is required.',
  validation_email_required: 'Your email is required.',
  validation_email_invalid: 'Please enter a valid email address.',
  validation_subject_required: 'A subject line is required.',
  validation_message_required: 'A message is required.',
  validation_message_too_short: 'Message is too short (min 10 chars).',
  validation_message_too_long: 'Message is too long (max 1000 chars).',
  footer_text: 'Designed & Built by Angesh Chanderdip',
  settings_title: 'Settings',
  settings_theme_title: 'Theme',
  settings_theme_desc: 'Toggle between light and dark mode.',
  settings_lang_title: 'Language',
  settings_lang_desc: 'Switch between English and French.'
};

const siteFr = {
  nav_about: 'À propos',
  nav_experience: 'Expérience',
  nav_projects: 'Projets',
  nav_education: 'Éducation',
  nav_contact: 'Contact',
  hero_greeting: "Bonjour, je m'appelle",
  hero_name: 'Angesh Chanderdip.',
  hero_subtitle: 'Je conçois un accès sécurisé pour un monde connecté.',
  hero_description: "Je suis un ingénieur en cybersécurité spécialisé dans le contrôle d'accès réseau et la sécurité des terminaux. Passionné par l'automatisation et avec une expérience éprouvée dans des environnements Fortune 500, je conçois et défends des cadres de sécurité robustes basés sur l'identité.",
  hero_cta: 'Contactez-moi',
  about_title: 'À propos de moi',
  about_description_1: "Bonjour ! Je suis Angesh, un professionnel de la cybersécurité passionné par la fluidification de l'accès sécurisé. J'adore travailler dans la cybersécurité car cela combine ce que j'apprécie le plus : comprendre comment les systèmes se connectent, prévoir où les choses pourraient mal tourner et m'assurer que les gens peuvent travailler en toute sécurité et sans heurts.",
  about_description_2: "Au fil des ans, je me suis concentré sur la sécurisation de l'accès au sein de grands réseaux complexes en utilisant des outils comme Cisco ISE, une protection robuste des terminaux et l'automatisation. Je suis convaincu que la sécurité ne devrait pas être un obstacle, mais qu'elle devrait améliorer le fonctionnement de tout. C'est pourquoi j'utilise des scripts et des flux de travail intelligents pour réduire les tâches répétitives et aider les équipes à réagir plus rapidement en cas de problème.",
  about_description_3: "En fin de compte, ma mission est simple : intégrer la confiance dans la technologie pour que les organisations puissent rester connectées, en sécurité et continuer à avancer.",
  about_description_4: "Sécurisons l'avenir — une connexion à la fois.",
  skills_title: 'Mon arsenal de compétences',
  experience_title: 'Où j\'ai travaillé',
  experience_professional_title: 'Expérience Professionnelle',
  experience_volunteer_title: 'Bénévolat et Communauté',
  projects_title: 'Ce que j\'ai construit',
  education_title: 'Éducation et certifications',
  education_tab_degree: 'Mon éducation',
  education_tab_certs: 'Certifications',
  education_tab_future: 'Projets futurs',
  future_plans_title: 'Apprentissage et croissance continus',
  future_plans_description: "Le paysage de la cybersécurité est en constante évolution, et moi aussi. Je m'engage à rester à la pointe de l'industrie. Voici mes directives stratégiques actuelles :",
  future_plans_isc2cc: "Établir une base complète et neutre vis-à-vis des fournisseurs en matière de principes de cybersécurité. Cette certification valide les connaissances essentielles dans des domaines clés, notamment les contrôles d'accès, la sécurité réseau, les opérations de sécurité et les principes fondamentaux de confidentialité, d'intégrité et de disponibilité requis for tout rôle en sécurité.",
  future_plans_ccna: "Atteindre la maîtrise des infrastructures réseau modernes en validant les compétences essentielles en accès réseau, connectivité IP et principes fondamentaux de sécurité. Cette certification consolidera l'expertise dans la configuration et la gestion des réseaux filaires et sans fil, la compréhension de l'automatisation du réseau et la mise en œuvre de politiques de sécurité fondamentales sur les équipements Cisco.",
  future_plans_az500: "Approfondir l'expertise en sécurité cloud en maîtrisant la mise en œuvre de contrôles de sécurité avancés et de la protection contre les menaces dans Microsoft Azure. Cela inclut la gestion de l'identité et des accès, la sécurisation des réseaux, le renforcement des machines virtuelles et l'orchestration des opérations de sécurité pour protéger les données, les applications et l'infrastructure à l'échelle de l'entreprise.",
  future_plans_az204: "Combler le fossé entre le développement et la sécurité en acquérant des compétences dans la création, le test et la maintenance d'applications cloud-natives sécurisées sur Azure. Les compétences clés incluent la mise en œuvre de solutions Azure sécurisées, le développement pour le stockage Azure et l'intégration de l'authentification et de l'autorisation pour intégrer la sécurité tout au long du cycle de vie du développement logiciel.",
  future_plans_competencies_title: 'Compétences Clés',
  cert_desc_btl1: "Valide les compétences pratiques pour la sécurité défensive du monde réel. Les titulaires ont démontré leur compétence en matière de renseignement sur les menaces, de surveillance de la sécurité du réseau, d'investigation numérique et de réponse aux incidents sur diverses plateformes.",
  cert_desc_sixsigma_white: "Fournit un aperçu fondamental de la méthodologie Six Sigma. Les White Belts comprennent les concepts de base, le vocabulaire et leurs rôles au sein d'une organisation axée sur la qualité, leur permettant de soutenir des projets d'amélioration.",
  cert_desc_sixsigma_yellow: "Valide une solide compréhension des principes Six Sigma. Les Yellow Belts sont des membres d'équipe précieux sur les projets, capables d'appliquer des outils de base, de collecter des données et de comprendre les cartographies de processus pour assister les Green et Black Belts.",
  cert_desc_sixsigma_green: "Démontre la maîtrise de la direction et de l'exécution de projets d'amélioration des processus. Les Green Belts sont des experts du cadre DMAIC, utilisant l'analyse statistique et les compétences en gestion de projet pour résoudre les problèmes de qualité et obtenir des résultats commerciaux tangibles.",
  cert_desc_sixsigma_black: "Le plus haut niveau de certification Six Sigma. Les Black Belts sont des experts en analyse statistique avancée et en direction de projet, capables de gérer des projets d'amélioration complexes et interfonctionnels qui entraînent des changements organisationnels et des avantages financiers significatifs.",
  cert_desc_cct: "Valide les compétences essentielles pour le support sur site et la maintenance des appareils réseau Cisco. Se concentre sur les services de réparation, le remplacement de matériel et la configuration pour restaurer les fonctionnalités, assurant la continuité opérationnelle.",
  cert_desc_az900: "Fournit une compréhension fondamentale des concepts du cloud et des services principaux de Microsoft Azure. Elle couvre les principes du cloud, l'architecture, la sécurité, la conformité et la tarification d'Azure.",
  cert_desc_isc2_candidate: "Reconnaît les individus en route vers une certification complète (ISC)², comme le CISSP. Cela signifie un engagement envers la profession de la cybersécurité et le respect du code d'éthique (ISC)².",
  cert_desc_cy_analyst: "Se concentre sur les compétences requises pour un analyste de Centre des Opérations de Sécurité (SOC), y compris la surveillance, la détection et l'analyse des menaces, en utilisant l'analyse comportementale pour combattre les APT.",
  cert_desc_cloud_plus: "Démontre les compétences nécessaires pour mettre en œuvre et maintenir les technologies cloud. Elle valide la connaissance des contrôles de sécurité, de la gestion de l'infrastructure et des meilleures pratiques pour déployer des environnements cloud sécurisés.",
  cert_desc_ccna: "Une certification de base en réseautique qui valide la capacité à installer, configurer, exploiter et dépanner des réseaux routés et commutés de taille moyenne, y compris la mise en œuvre de connexions vers des sites distants.",
  cert_desc_cissp_cns: "Couvre un domaine essentiel du CISSP, axé sur la sécurisation de l'architecture réseau, des canaux de communication et l'atténuation des attaques réseau. Valide l'expertise en protocoles, segmentation et sécurité sans fil.",
  cert_desc_win10_ad: "Démontre la compétence dans la gestion et la sécurisation des terminaux Windows 10 dans un environnement Active Directory. Couvre les objets de stratégie de groupe (GPO), la gestion des comptes utilisateurs et ordinateurs, et le dépannage de la connectivité client.",
  cert_desc_secplus_threats: "Se concentre sur l'identification et l'analyse des acteurs de la menace, des sources de renseignement et des vulnérabilités des systèmes. Cette certification valide la capacité à utiliser le renseignement sur les menaces pour soutenir la sécurité organisationnelle et chasser les menaces de manière proactive.",
  cert_desc_az_admin_aad: "Couvre les compétences de base pour l'administration d'Azure Active Directory, y compris la gestion des locataires et des domaines, Enterprise State Roaming, Identity Protection et la réinitialisation de mot de passe en libre-service (SSPR).",
  cert_desc_sec_risk_mgmt: "Valide l'expertise dans la gestion des contrôles de sécurité via une approche structurée, couvrant la gestion des risques, la sécurité des utilisateurs, la gestion des sessions et les techniques de chiffrement des données.",
  cert_desc_ws2016_gpo: "Valide la compétence dans la fonction, la configuration et le traitement des objets de stratégie de groupe (GPO) Active Directory pour la gestion de la configuration centralisée dans les environnements Windows Server 2016.",
  contact_title: 'Établir la Connexion',
  contact_subtitle: 'Me\ncontacter',
  contact_description: "Je suis toujours intéressé par de nouveaux défis et opportunités. Ma porte numérique est toujours ouverte. Que vous ayez une question, une proposition de projet ou simplement envie de vous connecter, n'hésitez pas à me contacter. Utilisez les relais directs pour un contact rapide ou le formulaire sécurisé pour une messagerie chiffrée.",
  contact_direct_relay_title: 'Relais Directs',
  contact_transmission_form_title: 'Transmission Sécurisée',
  contact_form_name: 'Votre Nom',
  contact_form_name_placeholder: 'ex: Ada Lovelace',
  contact_form_email: 'Votre E-mail',
  contact_form_email_placeholder: 'ex: utilisateur@domaine.com',
  contact_form_subject: 'Sujet',
  contact_form_subject_placeholder: 'Proposition de Projet',
  contact_form_message: 'Votre Message',
  contact_form_submit: 'Envoyer le Message',
  contact_sending_status: 'Transmission...',
  contact_success_title: 'Transmission Réussie',
  contact_success_desc: "Votre message a été relayé en toute sécurité. Merci de m'avoir contacté—je vous répondrai bientôt !",
  contact_error_title: 'Échec de la Transmission',
  contact_error_desc: "Un paquet de données a été perdu en chemin. Veuillez vérifier votre connexion et réessayer.",
  contact_send_another: 'Nouveau Message',
  contact_retry_button: 'Réessayer',
  validation_name_required: 'Votre nom est requis.',
  validation_email_required: 'Votre e-mail est requis.',
  validation_email_invalid: 'Veuillez entrer une adresse e-mail valide.',
  validation_subject_required: 'Un sujet est requis.',
  validation_message_required: 'Un message est requis.',
  validation_message_too_short: 'Message trop court (min 10 car.).',
  validation_message_too_long: 'Message trop long (max 1000 car.).',
  footer_text: 'Conçu et réalisé par Angesh Chanderdip',
  settings_title: 'Paramètres',
  settings_theme_title: 'Thème',
  settings_theme_desc: 'Basculez entre le mode clair et sombre.',
  settings_lang_title: 'Langue',
  settings_lang_desc: 'Passez de l\'anglais au français.'
};

fs.writeFileSync(path.join(contentEnDir, 'site.json'), JSON.stringify(siteEn, null, 2));
fs.writeFileSync(path.join(contentFrDir, 'site.json'), JSON.stringify(siteFr, null, 2));

console.log('Site files written');
